---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: docker.io/dahknesh232/testapps:pgs-dev-latest   # Use your tagged image from the local registry
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              value: "kyc-master"
            - name: POSTGRESQL_USER
              value: "keycloak"
            - name: POSTGRESQL_PASSWORD
              value: "mypassword"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: pgs-dev-service
  namespace: default
spec:
  selector:
    app: pgs-dev
  ports:
    - protocol: TCP
      port: 5432        # The port exposed by the Service
      targetPort: 5432  # The port to route to inside the Pods
  type: NodePort        