#!/bin/bash

# Generates git log and outputs to markdown file
#
# optional parameters
# -s, --since        to select start date
# -u, --until        to select end date

git-log-to-markdown() {
    local NEXT=$(date +%F)
    local SINCE="1969-01-01"
    local UNTIL=$NEXT

    for i in "$@"; do
        case $i in
            -s=*|--since=*)
            SINCE="${i#*=}"
            shift
            ;;
            -u=*|--until=*)
            UNTIL="${i#*=}"
            shift
            ;;
            *)
            # unknown option
            ;;
        esac
    done

    echo "# CHANGELOG.md"
    echo
    git log --since="${SINCE}" --until="${UNTIL}" --pretty=format:"## %cd%n** %s (%an)**%n- commit %H" --date=iso-strict | while IFS= read -r LINE; do
        echo -e "${LINE}"
        echo
    done
}

git-log-to-markdown "$@" > ../../CHANGELOG.md