# Use the official Keycloak image as the base image
FROM bitnami/postgresql:latest

# Set environment variables
ENV POSTGRESQL_USER: keycloak
ENV POSTGRESQL_PASSWORD: mysecretpassword
ENV POSTGRESQL_DATABASE=kyc-master

EXPOSE 5432