apiVersion: v1
kind: Service
metadata:
  name: kyc-iam-ports
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31010
  type: NodePort
